services:
  backend:
    build:
      context: ./backend
      dockerfile: Wedding.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB:-WeddingDb};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - SmtpSettings__Host=${SMTP_HOST:-mailpit}
      - SmtpSettings__Port=${SMTP_PORT:-1025}
      - SmtpSettings__Username=${SMTP_USERNAME:-}
      - SmtpSettings__Password=${SMTP_PASSWORD:-}
      - SmtpSettings__FromEmail=${SMTP_FROM_EMAIL:-ivanfigueredo.et@gmail.com}
      - SmtpSettings__FromName=${SMTP_FROM_NAME:-Nerea & Ivan}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wedding-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - wedding-network
    restart: always
    ports:
      - "8080:80"

  db:
    image: supabase/postgres:15.1.0.147
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-WeddingDb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-WeddingDb}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wedding-network
    restart: always

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - wedding-network
    restart: always

networks:
  wedding-network:
    driver: bridge

volumes:
  pg_data:
