FROM postgres:15-alpine
COPY init.sql /init.sql
ENTRYPOINT ["sh", "-c", "until psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c 'SELECT 1' > /dev/null 2>&1; do echo 'Esperando DB...'; sleep 2; done && psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f /init.sql"]
